### ISSUE TITLE
Delete Lieferant Endpoint

### ISSUE THREAD

**Issue by Shaco74** [Shaco74/SWE-MehrMarkt#30]
@majdbousaad Hi ich habe hier eine Issue für dich. Ich bräuchte in Backend einen DELETE Entpoint für Lieferanten.

Ich habe eine Lösch Funktion implementiert. Hier ein ausschinitt: 

```ts
onConfirm: async () => {
      console.log('delete')
      setIsConfirmDeleteShowing(false)
      await axios
        .delete(`http://localhost:8080/lieferant/${lieferant.id}`)
        .catch(() => {
          enqueueSnackbar('Es ist ein Fehler aufgetreten', { variant: 'error' })
        })
        .then(() => {
          fetchLieferanten()
          enqueueSnackbar('Lieferant wurde gelöscht', { variant: 'success' })
        })

      handleClose()
    },
```

Stell biette die URI `http://localhost:8080/lieferant/${lieferant.id}` zu verfügung

**Comment by majdbousaad** [comment]
Hey, Das Löschen eines Lieferanten ist nicht gefördert. Nur das Markieren als inaktiv

**Comment by Shaco74** [comment]
Okay dann schreibe ich das um in einen "set Lieferant inactive" button 👍 danke für die Klärung
